[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  # Default public demo broker (override in Netlify UI)
  VITE_DEFAULT_BROKER_WS = "wss://broker.hivemq.com:8000/mqtt"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Cache-Control = "public, max-age=3600"
